/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package estacionamento.preço;

import estacionamento.ConnectionFactory;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gustavo
 */
public class cadastroDePreco extends javax.swing.JFrame {

    /**
     * Creates new form cadastroDePreco
     */
    public cadastroDePreco() {
        initComponents();
    }
    
    public ArrayList<relatorioVeiculos> veiculos(){
        ArrayList<relatorioVeiculos> veiculos = new ArrayList<>();
        
        String sql = "SELECT * FROM preco_veiculo WHERE idprice <> ''";
        
        ConnectionFactory factory = new ConnectionFactory();
        try(Connection c = factory.obtemConexao()){
            PreparedStatement ps = c.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            
            relatorioVeiculos re;
            while (rs.next()) {
                re = new relatorioVeiculos(
                            rs.getString("veiculo"),
                            rs.getString("preco"));

                veiculos.add(re);
            }
        }catch (Exception e){
            e.printStackTrace();
        }
        return veiculos;
    }
    
    public void show_veiculos(){
        ArrayList<relatorioVeiculos> list = veiculos();
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        
        Object[] row = new Object[2];
        
        for(int i=0;i<list.size();i++){
            row[0]=list.get(i).getVeiculo();
            row[1]=list.get(i).getPreco();
            model.addRow(row);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        preco_TextField = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        veculo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zimagens/icons8-caixa-de-seleção-marcada-48.png"))); // NOI18N
        jButton1.setText("cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 190, 140, 43);
        getContentPane().add(preco_TextField);
        preco_TextField.setBounds(120, 110, 140, 22);

        jButton3.setText("Alterar");
        getContentPane().add(jButton3);
        jButton3.setBounds(200, 190, 80, 39);

        jButton4.setText("Deletar");
        getContentPane().add(jButton4);
        jButton4.setBounds(400, 190, 72, 39);
        getContentPane().add(veculo);
        veculo.setBounds(120, 70, 140, 22);

        jLabel1.setText("Veiculo");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 70, 60, 16);

        jLabel2.setText("Preço");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 110, 60, 16);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Veiculo", "Preço"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 250, 540, 190);

        jButton5.setText("Consulta");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(290, 190, 100, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if(veculo.getText().equals("VEICULOS")){
            JOptionPane.showMessageDialog(null, "Um dos campos não esta preenchido corretamente", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
            return;
        }else{
            try{
                
            String veiculo = (String) veculo.getText();

            cadastroPreco p = new cadastroPreco();
            p.setVeiculo(veiculo);
            
                ErroMenssagemVeiculo verificacao = new ErroMenssagemVeiculo(veiculo);
                if(verificacao.existeVeiculo(verificacao)){
                    JOptionPane.showMessageDialog(null, "Veiculo ja cadastrado.", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
                    return;
                } else {
                    String veiculoo = (String) veculo.getText();
                    String preco = preco_TextField.getText();

                    cadastroPreco p2 = new cadastroPreco();
                    p2.setVeiculo(veiculoo);
                    p2.setPreco(preco);
                    p2.inserir();

                    JOptionPane.showMessageDialog(null, "Veiculo cadastrado");
                }

            }catch(Exception e){
                e.printStackTrace();
            }
        }

        /**/
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        show_veiculos();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastroDePreco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastroDePreco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastroDePreco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastroDePreco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastroDePreco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField preco_TextField;
    private javax.swing.JTextField veculo;
    // End of variables declaration//GEN-END:variables
}
